### ISSUE TITLE
prometheus metrics

### ISSUE THREAD

**Issue by beorn-** [elwinar/rcoredump#1]
To allow admins to alert on crash dumps with meaningful alerts please add a new metric on rcoredumpd:
- per criterium or per criteria expose metric (tag with hostname, binary, hash/version)
- crash count

**Comment by elwinar** [comment]
I've added prometheus tooling, with a metric for the number of received crashes. For now it has two tags, hostname and executable (the full path of the binary as reported by the kernel).

I'm not sure the binary hash as a tag is really pertinent, so I'll delay it for now until I actually do a hashing system to save up on space for the binaries.
